language: java

jdk:
  - oraclejdk8

install:
  - ./gradlew sharp-processor:assemble

after_success:
  - ./gradlew sharp-api:check
  - ./gradlew sharp-processor:check

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle